services:
    _defaults:
        public: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    petzka_article_categories.listener.ajax:
        class: Petzka\DemoBundle\EventListener\AjaxListener
        arguments:
            - "@monolog.logger.contao"

    petzka_article_categories.listener.change_language:
        class: Petzka\DemoBundle\EventListener\ChangeLanguageListener
        arguments:
            - "@petzka_article_categories.manager"

    petzka_article_categories.listener.insert_tags:
        class: Petzka\DemoBundle\EventListener\InsertTagsListener
        arguments:
            - "@petzka_article_categories.manager"

    petzka_article_categories.listener.article:
        class: Petzka\DemoBundle\EventListener\ArticleListener
        arguments:
          - "@petzka_article_categories.article_criteria_builder"

    petzka_article_categories.listener.template:
        class: Petzka\DemoBundle\EventListener\TemplateListener
        arguments:
            - "@petzka_article_categories.manager"

    # Data container
    petzka_article_categories.listener.data_container.content:
        class: Petzka\DemoBundle\EventListener\DataContainer\ContentListener
        arguments:
            - "@database_connection"


    petzka_article_categories.listener.data_container.article_category:
        class: Petzka\DemoBundle\EventListener\DataContainer\ArticleCategoryListener
        arguments:
            - "@database_connection"
            - "@petzka_article_categories.permission_checker"
            - "@session"

    petzka_article_categories.listener.data_container.article:
        class: Petzka\DemoBundle\EventListener\DataContainer\ArticleListener
        arguments:
            - "@database_connection"
            - "@petzka_article_categories.permission_checker"
